### ISSUE TITLE
Build Tiling NavMesh with Off Mesh Link throw error

### ISSUE THREAD

**Issue by weilichuang** [ppiastucki/recast4j#110]
![off-mesh link error](https://user-images.githubusercontent.com/2355262/117530070-ba348680-b00d-11eb-80a3-ad05787cea81.png)

Add a Off-Mesh Link then click build will throw error.

`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
        at org.recast4j.detour.NavMesh.connectExtOffMeshLinks(NavMesh.java:700)
        at org.recast4j.detour.NavMesh.addTile(NavMesh.java:470)
        at org.recast4j.demo.builder.TileNavMeshBuilder.lambda$buildNavMesh$0(TileNavMeshBuilder.java:94)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.recast4j.demo.builder.TileNavMeshBuilder.buildNavMesh(TileNavMeshBuilder.java:94)
        at org.recast4j.demo.builder.TileNavMeshBuilder.build(TileNavMeshBuilder.java:60)
        at org.recast4j.demo.RecastDemo.start(RecastDemo.java:255)
        at org.recast4j.demo.RecastDemo.main(RecastDemo.java:585)`

**Comment by ppiastucki** [comment]
Thank you for the information. Unfortunately, I cannot reproduce the issue. I would be grateful if you could provide a test case which can be used to reproduce it.
