### ISSUE TITLE
Error when running on ubuntu

### ISSUE THREAD

**Issue by DangTu97** [ppiastucki/recast4j#120]
Hi, I am facing this problem when trying to run a demo on Ubuntu 20.04: 

java -jar recast-demo-1.5.3-SNAPSHOT-all.jar

      Exception in thread "main" java.lang.IllegalArgumentException 
	      at java.base/java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1293)
	      at java.base/java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1215)
	      at java.base/java.util.concurrent.Executors.newFixedThreadPool(Executors.java:155)
	      at org.recast4j.demo.builder.TileNavMeshBuilder.<init>(TileNavMeshBuilder.java:46)
	      at org.recast4j.demo.RecastDemo.<init>(RecastDemo.java:96)
	      at org.recast4j.demo.RecastDemo.main(RecastDemo.java:584)

Do you know how to fix this problem? Thank you in advance.

**Comment by ppiastucki** [comment]
Please provide exact steps to reproduce

**Comment by DangTu97** [comment]
You are totally right. It's fine now after I have increased the number of processors. Thank you so much.
