### ISSUE TITLE
DetourCommon.vLerp(DetourCommon.java:56) java.lang.NullPointerException

### ISSUE THREAD

**Issue by xuxiaohua666** [ppiastucki/recast4j#125]
x:73284 y:22948

java.lang.NullPointerException: null
	at org.recast4j.detour.DetourCommon.vLerp(DetourCommon.java:56) ~[detour-1.5.3-SNAPSHOT.jar:1.5.3-SNAPSHOT]
	at org.recast4j.detour.NavMesh.closestPointOnDetailEdges(NavMesh.java:1028) ~[detour-1.5.3-SNAPSHOT.jar:1.5.3-SNAPSHOT]
	at org.recast4j.detour.NavMesh.closestPointOnPoly(NavMesh.java:1120) ~[detour-1.5.3-SNAPSHOT.jar:1.5.3-SNAPSHOT]
	at org.recast4j.detour.NavMeshQuery.closestPointOnPoly(NavMeshQuery.java:408) ~[detour-1.5.3-SNAPSHOT.jar:1.5.3-SNAPSHOT]
	at org.recast4j.detour.FindNearestPolyQuery.process(FindNearestPolyQuery.java:25) ~[detour-1.5.3-SNAPSHOT.jar:1.5.3-SNAPSHOT]
	at org.recast4j.detour.NavMeshQuery.queryPolygonsInTile(NavMeshQuery.java:570) ~[detour-1.5.3-SNAPSHOT.jar:1.5.3-SNAPSHOT]
	at org.recast4j.detour.NavMeshQuery.lambda$queryPolygons$0(NavMeshQuery.java:632) ~[detour-1.5.3-SNAPSHOT.jar:1.5.3-SNAPSHOT]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_261]
	at org.recast4j.detour.NavMeshQuery.queryPolygons(NavMeshQuery.java:632) ~[detour-1.5.3-SNAPSHOT.jar:1.5.3-SNAPSHOT]
[aol_nav_5.bin.zip](https://github.com/ppiastucki/recast4j/files/8529879/aol_nav_5.bin.zip)

	at org.recast4j.detour.NavMeshQuery.findNearestPoly(NavMeshQuery.java:526) ~[detour-1.5.3-SNAPSHOT.jar:1.5.3-SNAPSHOT]

**Comment by ppiastucki** [comment]
Thanks for reporting
