### ISSUE TITLE
Unable to run the .jar in macOS

### ISSUE THREAD

**Issue by ivnnv** [ppiastucki/recast4j#78]
Hi,

I tried to run the demo but it is not working on macOS 10.15.7
```
 java -jar recast-demo-1.2.2-SNAPSHOT.jar                                                                                                        20:32:25
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1831)
	at org.recast4j.demo.RecastDemo.start(RecastDemo.java:220)
	at org.recast4j.demo.RecastDemo.main(RecastDemo.java:593)
Caused by: java.lang.IllegalStateException: GLFW windows may only be created on the main thread and that thread must be the first thread in the process. Please run the JVM with -XstartOnFirstThread. For offscreen rendering, make sure another window toolkit (e.g. AWT or JavaFX) is initialized before GLFW.
	at org.lwjgl.glfw.EventLoop$OffScreen.<clinit>(EventLoop.java:39)
	... 3 more
```
^ The above seems to be solved adding `-XstartOnFirstThread`

And then:
```
user@machine:/Users/user/Desktop/recast4j-parent-1.2.5/recast-demo/target: java -XstartOnFirstThread -jar recast-demo-1.2.2-SNAPSHOT.jar                                                                                  20:32:34
20:36:06.321 [main] DEBUG org.recast4j.demo.RecastDemo - Intel Inc.
20:36:06.323 [main] DEBUG org.recast4j.demo.RecastDemo - 2.1 INTEL-14.7.8
20:36:06.323 [main] DEBUG org.recast4j.demo.RecastDemo - Intel(R) Iris(TM) Plus Graphics 655
20:36:06.323 [main] DEBUG org.recast4j.demo.RecastDemo - 1.20
Exception in thread "main" java.lang.IllegalStateException
	at org.recast4j.demo.ui.NuklearGL.<init>(NuklearGL.java:184)
	at org.recast4j.demo.ui.NuklearUI.<init>(NuklearUI.java:89)
	at org.recast4j.demo.RecastDemo.start(RecastDemo.java:331)
	at org.recast4j.demo.RecastDemo.main(RecastDemo.java:593)
```

Which is throwing at:
`if (glGetShaderi(vert_shdr, GL_COMPILE_STATUS) != GL_TRUE) {`

Do you know why?

PS: It never runs on a windows Virtualbox Windows 10 machine which shows as the graphic device: 
```
23:32:14.486 [main] DEBUG org.recast4j.demo.RecastDemo - VMware, Inc.
23:32:14.486 [main] DEBUG org.recast4j.demo.RecastDemo - 2.1 Mesa mesa-17.3.9
23:32:14.486 [main] DEBUG org.recast4j.demo.RecastDemo - SVGA3D; build: RELEASE;
23:32:14.486 [main] DEBUG org.recast4j.demo.RecastDemo - 1.20
```
And then the same error for `NuklearGL.java:184`

**Comment by ppiastucki** [comment]
Hi, 
The following entry in the logs contains the version of the GLSL:
```
23:32:14.486 [main] DEBUG org.recast4j.demo.RecastDemo - 1.20
```
The shaders used in RecastDemo require GLSL 1.5 or higher. The code tries to ensure the proper version of the GLSL by settings the following:
```
        glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
        glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
```
but apparently it is not respected on your device.

**Comment by ppiastucki** [comment]
Closing inactive issue
